package com.nordnetab.chcp.main.events;

import com.nordnetab.chcp.main.config.ApplicationConfig;
import com.nordnetab.chcp.main.config.DownLoadEventData;
import com.nordnetab.chcp.main.model.ChcpError;

import java.util.Map;
import org.json.JSONObject;
import org.json.JSONException;
/**
 * Created by Nikolay Demyankov on 28.08.15.
 * <p/>
 * Base class for events, that generated by installation/download workers.
 *
 * @see com.nordnetab.chcp.main.updater.InstallationWorker
 * @see com.nordnetab.chcp.main.updater.UpdateLoaderWorker
 * @see IPluginEvent
 */
public class WorkerEvent extends PluginEventImpl {

    private static final String CONFIG_KEY = "config";
    private static final String TASK_DETAIL_KEY = "taskDetail";
    /**
     * Class constructor
     *
     * @param eventName string identifier of the event
     * @param error     error information
     * @param appConfig application config which this worker used
     * @see ChcpError
     * @see ApplicationConfig
     */
    protected WorkerEvent(String eventName, ChcpError error, ApplicationConfig appConfig) {
        super(eventName, error);

        if (appConfig != null) {
            data().put(CONFIG_KEY, appConfig);
        }
    }
    protected WorkerEvent(String eventName, DownLoadEventData downloadEventData ) {
        super(eventName, null);
      
        if(downloadEventData != null) 
        {
          data().put(TASK_DETAIL_KEY, downloadEventData);
        }
        
    }

    /**
     * Getter for application config, attached to this event.
     * This config was used to perform download/installation work.
     *
     * @return application config
     */
    public ApplicationConfig applicationConfig() {
        final Map<String, Object> eventData = data();
        if (!eventData.containsKey(CONFIG_KEY)) {
            return null;
        }

        return (ApplicationConfig) eventData.get(CONFIG_KEY);
    }

     /**
     * Getter for application task detail, attached to this event.
     * This task detail was used to perform download task work.
     *
     * @return task detail
     */
    public DownLoadEventData downLoadEventData() {
        final Map<String, Object> eventData = data();
        if (!eventData.containsKey(TASK_DETAIL_KEY)) {
          return null;
        }
 
        return (DownLoadEventData) eventData.get(TASK_DETAIL_KEY);
    }
}